drop database if exists TESTES;

CREATE DATABASE TESTES;

USE TESTES;

CREATE TABLE USUARIO(
ID_USUARIO INT AUTO_INCREMENT,
USUARIO VARCHAR(50) NOT NULL,
SENHA VARCHAR(30) NOT NULL,
PRIMARY KEY(ID_USUARIO)
);

CREATE TABLE LOGUI( #A palavra Log é reservada
ID_LOG INT AUTO_INCREMENT,
TEXTO VARCHAR(300) NOT NULL,
TEMPO DATE NOT NULL,
USUARIO_LOG VARCHAR(50) NOT NULL,
PRIMARY KEY(ID_LOG)
);


CREATE TABLE EVENTOS(
ID_EVENTO INT AUTO_INCREMENT,
TEMPO_EVENTO DATE NOT NULL,
NOME_EVENTO VARCHAR(50) NOT NULL,
PRIMARY KEY(ID_EVENTO)
);

CREATE TABLE PRODUTO(
ID_PRODUTO INT AUTO_INCREMENT,
NOME_PRODUTO VARCHAR(50) NOT NULL,
SITUACAO BOOLEAN,
OBS VARCHAR(100), #Observação
PRIMARY KEY(ID_PRODUTO)
);


CREATE TABLE TESTADORES(
ID_TESTADOR INT AUTO_INCREMENT,
NOME_TESTADOR VARCHAR(50) NOT NULL,
CPF VARCHAR(30) NOT NULL,
IDADE INT NOT NULL,
PRIMARY KEY(ID_TESTADOR)
);


CREATE TABLE TESTADOR_PRODUTO(
ID_TEST_PROD INT AUTO_INCREMENT,
ID_TESTADOR INT NOT NULL,
ID_PRODUTO INT NOT NULL,
PRIMARY KEY(ID_TEST_PROD),
CONSTRAINT FK_TESTADOR_PRODUTO FOREIGN KEY (ID_TESTADOR) REFERENCES TESTADORES(ID_TESTADOR),
CONSTRAINT FK_PRODUTO_TESTADOR FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO) 
);

CREATE TABLE TESTADOR_EVENTO(
ID_TEST_EVEN INT AUTO_INCREMENT,
ID_TESTADOR INT NOT NULL,
ID_EVENTO INT NOT NULL,
PRIMARY KEY(ID_TEST_EVEN),
CONSTRAINT FK_TESTADOR_EVENTO FOREIGN KEY (ID_TESTADOR) REFERENCES TESTADORES(ID_TESTADOR),
CONSTRAINT FK_EVENTO_TESTADOR FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS (ID_EVENTO)
);

INSERT INTO USUARIO VALUES(DEFAULT, 'ADM', '123');
